---
sudo: false
language: ruby
cache: bundler
rvm:
 - 2.1.10
 - 2.2.4
 - 2.4.1
 - 2.5.3
if: branch = master OR type = pull_request
env:
  global:
    - CC_TEST_REPORTER_ID=54ccd23af92d7903f1aebe01a8b5cbe272d7672fc636d0351527fd123d60f04e
    - CI=true
before_install:
  - gem install bundler -v 1.17.3
  - bin/setup
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bin/test
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
