---
sudo: false
language: ruby
cache: bundler
rvm:
 - 2.1.10
 - 2.2.4
 - 2.4.1
 - 2.5.3
 - 2.6.3
if: branch = master OR type = pull_request
env:
  global:
    - CC_TEST_REPORTER_ID=88a7fd75659a6698f28c8c4c6b60c20f902e26733691b2fe449a65474f22b618
    - CI=true
before_install:
  - bin/setup
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bin/test
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
